# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "onjs+6dnADFmN3AXwAkWuABMqmwJAIerP982q3fzSMMMmUjebB1UcsTVovLlSmh096t7zxm+vHS57ZdKLdIlDT4x4JRwZlXcmToZBGB52hDQZO9RDuFZgjotRFh+F44pztNiX6iY3MyIzgOa3fdsP1armRlENg4whvyt0MlGZa4v04KWpuIdpvMPjne8FHUuaWZFmUpe6/DK/VYGg/avJhGpp29IFvKJOKiE4GTFjytuu7jfHNzdw7D33JFmfrDub0aTq9niZFPop9OeLxEs5LVcRbvZPMrFiOdzFvT5cvDD1DNYduFiTqmCSpGR7P/6E8fXlo9qpKxmH5YoM1m5iYiGGipIQDNggFSPLSCNIoxTRMPsV8aIyiIi44rSZrcmHjUCwiNiGc/OR8M036JG+saalm+Me0AbFicFvl6NsCLsAdins+w7RwIT5dDoEwPUrM7X2ltZSMZMVlchpqtoLum0y/jHnug2RZe3Xn9D5w2SsWiVHpxV9PdF1MwRPCQqQjiRbksQhzzX6acXuQ0xoUdXE7Yv4u3DAPnHDllh0mdI/1A6x5zLlHX5YtZkQXctswtRLtR70zEch7LjUb7TVn2/8CCK3XV+GadzU7tjkmGNXmPEhWIXEgeB+jRekNqVfgvtNdgZaCrt96DcyMDzZIT3/ElI2RciKVIzQSPSr74="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
