travis:
  secure:
    BINSTAR_TOKEN: onjs+6dnADFmN3AXwAkWuABMqmwJAIerP982q3fzSMMMmUjebB1UcsTVovLlSmh096t7zxm+vHS57ZdKLdIlDT4x4JRwZlXcmToZBGB52hDQZO9RDuFZgjotRFh+F44pztNiX6iY3MyIzgOa3fdsP1armRlENg4whvyt0MlGZa4v04KWpuIdpvMPjne8FHUuaWZFmUpe6/DK/VYGg/avJhGpp29IFvKJOKiE4GTFjytuu7jfHNzdw7D33JFmfrDub0aTq9niZFPop9OeLxEs5LVcRbvZPMrFiOdzFvT5cvDD1DNYduFiTqmCSpGR7P/6E8fXlo9qpKxmH5YoM1m5iYiGGipIQDNggFSPLSCNIoxTRMPsV8aIyiIi44rSZrcmHjUCwiNiGc/OR8M036JG+saalm+Me0AbFicFvl6NsCLsAdins+w7RwIT5dDoEwPUrM7X2ltZSMZMVlchpqtoLum0y/jHnug2RZe3Xn9D5w2SsWiVHpxV9PdF1MwRPCQqQjiRbksQhzzX6acXuQ0xoUdXE7Yv4u3DAPnHDllh0mdI/1A6x5zLlHX5YtZkQXctswtRLtR70zEch7LjUb7TVn2/8CCK3XV+GadzU7tjkmGNXmPEhWIXEgeB+jRekNqVfgvtNdgZaCrt96DcyMDzZIT3/ElI2RciKVIzQSPSr74=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
